name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  release:
    types: [published]

jobs:
  build:
    name: Build
    if: contains(fromJSON('["push", "pull_request"]'), github.event_name)
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      - name: Submit Dependency Snapshot
        uses: advanced-security/maven-dependency-submission-action@v4

  release:
    name: Release
    if: contains(fromJSON('["release"]'), github.event_name)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Set version from release tag
        run: mvn -B versions:set -DnewVersion=${{ github.event.release.tag_name }} -DgenerateBackupPoms=false

      - name: Build and package with Maven
        run: mvn -B clean package --file pom.xml

      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: target/BankAccounts-${{ github.event.release.tag_name }}.jar application/java-archive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to Modrinth
        uses: cloudnode-pro/modrinth-publish@refactor
        with:
          api-domain: 'staging-api.modrinth.com'
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: vDt2IvQQ
          name: ${{ github.event.release.name }}
          version: ${{ github.event.release.tag_name }}
          changelog: ${{ github.event.release.body }}
          loaders: paper
          game-versions: |-
            1.20.x
            1.21.x
          files: target/BankAccounts-${{ github.event.release.tag_name }}.jar
